# Generated by Django 5.2.5 on 2025-10-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_attachment_bid_conversation_message_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='milestonoes',
            new_name='milestones',
        ),
    ]
