# Generated by Django 5.2.5 on 2025-10-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_rename_milestonoes_order_milestones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='milestones',
            field=models.JSONField(blank=True),
        ),
    ]
