# Generated by Django 5.2.5 on 2025-10-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_alter_order_milestones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='milestones',
        ),
    ]
