# Generated by Django 5.2.5 on 2025-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_remove_order_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='milestones',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
