# Generated by Django 5.2.5 on 2025-10-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.bid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed')], default='IN_PROGRESS', max_length=20),
        ),
    ]
