# Generated by Django 5.2.5 on 2025-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_order_bid_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed')], default='IN PROGRESS', max_length=20),
        ),
    ]
