services:
  - type: web
    name: gighub-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Gighub.wsgi
    plan: free
    region: oregon
    runtime: python
