# Generated by Django 5.2.5 on 2025-09-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_attachment_bid_conversation_message_order_and_more'),
        ('Freelancer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gig',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
